version: "3.8"

services:
  frontend:
    image: app-frontend-prod:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    tty: false

volumes:
  caddy_data:
  caddy_config: