version: "3.8"
# This file defines high-level environment variables for the stack.

services:
  frontend:
    image: app-frontend-dev:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app
      - ./public:/usr/src/app/public
      - ./vite.config.js:/usr/src/app/vite.config.js
      - ./index.html:/usr/src/app/public/index.html
      - ./package.json:/usr/src/app/package.json
      - caddy_data:/data
      - caddy_config:/config
    tty: true

volumes:
  caddy_data:
  caddy_config: