# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.adapter.coindesk_rss:
        class: App\Adapter\RssAdapter
        arguments:
            $sourceId: 'coindesk-rss'
            $feedUrl: 'https://www.coindesk.com/arc/outboundfeeds/rss/'
        tags: ['app.source_adapter']

    app.adapter.cointelegraph_rss:
        class: App\Adapter\RssAdapter
        arguments:
            $sourceId: 'cointelegraph-rss'
            $feedUrl: 'https://cointelegraph.com/rss'
        tags: ['app.source_adapter']

    App\MessageHandler\IngestSourceHandler:
        arguments:
            $adapters: !tagged_iterator app.source_adapter
