# Development overrides
services:
  database:
    ports:
      - "5432:5432"

  backend:
    image: app-backend-dev:1.0
    build:
      target: frankenphp_dev
    ports:
      - "80:80"
    volumes:
      - ./backend/src:/app/src
      - ./backend/frankenphp/Caddyfile:/etc/caddy/Caddyfile
      - ./backend/frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      - ./backend/config:/app/config
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: development
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true

  frontend:
    image: app-frontend-dev:1.0
    build:
      target: development
      args:
        NODE_ENV: development
    environment:
      - VITE_API_URL=http://backend:80
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true