# Production environment override
services:
  php:
    image: app-backend-prod:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: frankenphp_prod
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION}
        STABILITY: ${STABILITY}
    env_file:
      - .env
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      APP_ENV: production
      
      
