# Development environment override
services:
  backend:
    image: app-backend-dev:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: frankenphp_dev
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION}
        STABILITY: ${STABILITY}
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
      - ./config/jwt:/app/config/jwt
      - ./config/packages:/app/config/packages
#      - ./config/mercure:/app/config/mercure Uncomment if MercureBundle is installed.
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: development
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
