services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      - FRANKENPHP_CONFIG=${FRANKENPHP_CONFIG:-import worker.Caddyfile}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    
# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  caddy_data:
  caddy_config:
