<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260601054114 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create news_item and enrichment tables; HNSW index on embedding for semantic search';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE news_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source VARCHAR(64) NOT NULL, external_id VARCHAR(512) NOT NULL, title VARCHAR(512) NOT NULL, url VARCHAR(2048) NOT NULL, body TEXT DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, content_hash VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_content_hash ON news_item (content_hash)');
        $this->addSql('CREATE INDEX idx_news_item_status ON news_item (status)');
        $this->addSql('CREATE INDEX idx_news_item_published_at ON news_item (published_at)');
        $this->addSql('CREATE TABLE enrichment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, news_item_id INT NOT NULL, summary TEXT NOT NULL, sentiment VARCHAR(16) NOT NULL, asset_class VARCHAR(64) DEFAULT NULL, tickers JSON NOT NULL, entities JSON NOT NULL, embedding vector(1024) DEFAULT NULL, model VARCHAR(64) NOT NULL, tokens INT NOT NULL, cost_usd NUMERIC(10, 6) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BCDAF6CE458B4EB8 ON enrichment (news_item_id)');
        $this->addSql('ALTER TABLE enrichment ADD CONSTRAINT FK_BCDAF6CE458B4EB8 FOREIGN KEY (news_item_id) REFERENCES news_item (id) ON DELETE CASCADE NOT DEFERRABLE');
        // HNSW index for cosine similarity search — only rows with a non-null embedding are indexed
        $this->addSql('CREATE INDEX hnsw_enrichment_embedding ON enrichment USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE enrichment DROP CONSTRAINT FK_BCDAF6CE458B4EB8');
        $this->addSql('DROP TABLE enrichment');
        $this->addSql('DROP TABLE news_item');
    }
}
